language: node_js
node_js:
  - "node"
  - "8"
  - "6"

# Cache dependencies in $HOME/.yarn-cache across builds
cache: yarn

# Go to the final step before install
before_install: cd end

# Run the dummy test
script: yarn test
